---
- name: Configure Elasticsearch
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  with_items:
    - '{{ ansible_eth1["ipv4"]["address"] }}'
  notify: restart elasticsearch
