---

- name: Creating webroots
  file: >
    dest=/var/www/{{ item.id }}/htdocs
    state=directory
  when: item.add_webroot is defined and item.add_webroot == true
  with_items: apache2_sites
  tags:
    - web
    - apache2-php
    - manage

# site
- name: Creating sites
  template: >
    src={{ item.template|default(apache2_version ~ '/etc-apache2-sites-available-site.j2') }}
    dest=/etc/apache2/sites-available/{{ item.id }}{{ apache2_site_conf_extension }}
    owner=root
    group=root
    mode=0644
  with_items: apache2_sites
  tags:
    - web
    - apache2-php
    - manage

- name: Enabling sites
  file: >
    src=/etc/apache2/sites-available/{{ item.id }}{{ apache2_site_conf_extension }}
    dest=/etc/apache2/sites-enabled/{{ item.id }}{{ apache2_site_conf_extension }}
    state=link
  when: item.state is not defined or item.state == 'present'
  with_items: apache2_sites
  notify: reload apache2
  tags:
    - web
    - apache2
    - manage_sites

- name: Disabling sites
  file: >
    src=/etc/apache2/sites-enabled/{{ item.id }}{{ apache2_site_conf_extension }}
    state=absent
  when: item.state is defined and item.state == 'absent'
  with_items: apache2_sites
  notify: reload apache2
  tags:
    - web
    - apache2
    - manage_sites
