---

- name: Enabling conf
  command: >
    a2enconf {{ item.id }}
    creates=/etc/apache2/conf-enabled/{{ item.id }}.conf
  when: item.state is not defined or item.state != 'absent'
  with_items: apache2_confs
  notify: reload apache2
  tags:
    - web
    - apache2
    - manage_confs

- name: Disabling conf
  command: >
    a2disconf {{ item.id }}
    removes=/etc/apache2/conf-enabled/{{ item.id }}.conf
  when: item.state is defined and item.state == 'absent'
  with_items: apache2_confs
  notify: reload apache2
  tags:
    - web
    - apache2
    - manage_confs
