---

- name: Disabling default host
  file: >
    dest=/etc/apache2/sites-enabled/000-default
    state=absent
  notify: reload apache2
  when: apache2_remove_default
  tags:
    - web
    - apache2
    - remove_default

- name: Removing default host
  file: >
    dest=/etc/apache2/sites-available/default
    state=absent
  when: apache2_remove_default
  tags:
    - web
    - apache2
    - remove_default

- name: Removing default-ssl host
  file: >
    dest=/etc/apache2/sites-available/default-ssl
    state=absent
  when: apache2_remove_default
  tags:
    - web
    - apache2
    - remove_default
