---

- name: Adding rules
  copy: >
    src={{ apache2_version }}/etc-apache2-rules/
    dest=/etc/apache2/rules/
    owner=root
    group=root
    mode=0644
  tags:
    - web
    - apache2
    - rules