---

nginx_sites:
  homestead.local.typo3.org:
    - set $upstream hhvm
    - listen 80 default_server
    - server_name _
    - root "{{ typo3_webroot }}/homestead.local.typo3.org/"
    - "{{ nginx_fastcgi }}"
  homestead.local.typo3.org.ssl:
    - set $upstream php
    - listen 443 default_server
    - server_name _
    - root "{{ typo3_webroot }}/homestead.local.typo3.org/"
    - "{{ nginx_fastcgi }}"
    - ssl on
    - ssl_certificate /etc/ssl/certs/local.typo3.org.crt
    - ssl_certificate_key /etc/ssl/private/local.typo3.org.key
  typo3.cms:
    - set $upstream php
    - server_name ~(?<version>.*)\.local.typo3.org$
    - root "{{ typo3_webroot }}${version}.local.typo3.org/";
    - "{{ nginx_fastcgi }}"
  typo3.cms.ssl:
    - set $upstream php
    - listen 443
    - server_name ~(?<version>.*)\.local.typo3.org$
    - root "{{ typo3_webroot }}${version}.local.typo3.org/";
    - ssl on
    - ssl_certificate /etc/ssl/certs/local.typo3.org.crt
    - ssl_certificate_key /etc/ssl/private/local.typo3.org.key
    - "{{ nginx_fastcgi }}"
