---

- name: Disable atime on root filesystem
  mount: name=/ src=/dev/sda1 fstype=ext4 opts=rw,noatime state=mounted

- name: Setup ubuntu mirrors
  lineinfile: dest=/etc/apt/sources.list line="deb mirror://mirrors.ubuntu.com/mirrors.txt {{ item }} main restricted universe multiverse" insertbefore=BOF state=present
  with_items:
    - trusty
    - trusty-updates
    - trusty-backports
    - trusty-security

- name: Update apt package lists
  apt:
    update_cache: yes
    cache_valid_time: "{{ homestead.cache_valid_time }}"
  when: homestead.update_cache

- name: Upgrade all packages
  apt: upgrade=dist
  when: homestead.upgrade_packages

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget

- name: Autoremove unused packages
  command: apt-get -y autoremove --purge

- name: Install Some PPAs - software-properties-common
  apt: name=software-properties-common state=present

- name: Add package repositories
  apt_repository: repo={{ item }}
  with_items:
    - "ppa:nginx/development"
    - "ppa:ondrej/php"
    - "ppa:chris-lea/node.js"

- name: Update apt
  apt: update_cache=yes

- name: Install Extra Packages
  apt: pkg={{ item }} state=latest
  with_items: "{{ sys_packages }}"

- name: Configure the timezone
  template: src=timezone.tpl.j2 dest=/etc/timezone

- name: More Configure the timezone
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set the hostname in /etc/hostname
  shell: echo 'local.typo3.org' > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname 'local.typo3.org'
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost local.typo3.org' owner=root group=root mode=0644
  when: hostname is defined

- name: Setup locales
  locale_gen: name={{ item }} state=present
  with_items: ['de_DE.UTF-8', 'en_GB.UTF-8', 'nl_NL.UTF-8']

- name: Setup dircolors
  become: vagrant
  copy: src=dircolors dest=~/.dircolors force=no

- name: Setup postfix as a null mailer
  copy: src=postfix_main.cf dest=/etc/postfix/main.cf force=no

- name: Start the postfix service
  service: name=postfix state=started enabled=yes
  tags: [service,postfix]

- include: ramdisk.yml
  tags: ramdisk

- include: ssh.yml
  tags: ssh

- include: ssl.yml
  tags: ssl

- include: zsh.yml
  when: homestead.use_zsh
  tags: zsh

- include: rabbitmq.yml
  tags: rabbitmq
  when: context == "Development"

- include: shellinabox.yml
  tags: shellinabox
  when: context == "Development"
