---

- name: Create CMS databases
  mysql_db: name={{ item.key | regex_replace('\\.', '_') }}
            state=present
            encoding='utf8'
  with_dict: typo3.cms.sites

- name: Grant CMS database privileges
  mysql_user: name={{ mariadb.user }}
              password={{ mariadb.password }}
              priv={{ item.key | regex_replace('\\.', '_') }}.*:ALL
              append_privs=yes
  with_dict: typo3.cms.sites

- name: Create NEOS databases
  mysql_db: name={{ item.key | regex_replace('\\.', '_') }}
            state=present
            encoding='utf8'
  with_dict: typo3.neos.sites

- name: Grant NEOS database privileges
  mysql_user: name={{ mariadb.user }}
              password={{ mariadb.password }}
              priv={{ item.key | regex_replace('\\.', '_') }}.*:ALL
              append_privs=yes
  with_dict: typo3.neos.sites
