---
  typo3_cms_src_repository: 'https://git.typo3.org/Packages/TYPO3.CMS.git'

  typo3_cms_src_push_url: 'git://git.typo3.org/Packages/TYPO3.CMS.git'

  typo3_org_username: anonymous

  typo3_composer_install_dev: 'no'

  typo3_composer_preferred_install: 'dist'

  # Workaround variable to get a left curly brace next to a pound into a template file
  typo3_left_curly_brace: '{'

  typo3_webroot: '/var/www/'

  typo3_ssl_certificates:
    - '*.local.typo3.org'

  typo3:
    cms:
      sites: {}
      extensions:
        disabled: []
        enabled: []
