---

php_ini:
  - option: "engine"
    section: "PHP"
    value: "1"
  - option: "error_reporting"
    section: "PHP"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - option: "expose_php"
    section: "PHP"
    value: "On"
  - option: "date.timezone"
    section: "PHP"
    value: "{{ timezone }}"
  - option: "max_execution_time"
    section: "PHP"
    value: 240
  - option: "upload_max_filesize"
    section: "PHP"
    value: "20M"
  - option: "post_max_size"
    section: "PHP"
    value: "20M"
  - option: "soap.wsdl_cache_dir"
    section: "soap"
    value: "/tmp"
  - option: "pdo_mysql.cache_size"
    section: "Pdo_mysql"
    value: "2000"
  - option: "sendmail_path"
    section: "mail function"
    value: "/opt/mailhog/mailhog"