---

- name: Get composer installer
  get_url: dest=/tmp/composer-setup.php url=https://getcomposer.org/installer

- name: Check composer installer
  command: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;"

- name: Install composer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer && php -r "unlink('/tmp/composer-setup.php');"
