---

- name: Install Extra Packages
  apk: name={{ item }} state=present update_cache=yes
  with_items: "{{ sys_packages }}"

- name: Add earth apk repository key
  get_url: dest=/etc/apk/keys/phpearth.rsa.pub url=https://repos.php.earth/alpine/phpearth.rsa.pub

- name: Test for earth repository
  shell: grep "^https://repos.php.earth" /etc/apk/repositories | wc -l
  register: earth_grep

- debug: msg="{{earth_grep.stdout}}"

- name: Add earth repository
  lineinfile: dest=/etc/apk/repositories line="https://repos.php.earth/alpine/v3.7"
  when: earth_grep.stdout != ""

- name: Add earth packages
  apk: name={{ item }} state=latest update_cache=yes
  with_items: "{{ earth_packages }}"

- name: Set the hostname in /etc/hostname
  shell: echo 'local.typo3.org' > /etc/hostname

- name: Set the hostname
  command: hostname 'local.typo3.org'

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost local.typo3.org' owner=root group=wheel mode=0644

- name: Setup dircolors
  become: vagrant
  copy: src=dircolors dest=~/.dircolors force=no

#- name: Setup postfix as a null mailer
#  copy: src=postfix_main.cf dest=/etc/postfix/main.cf force=no
#
#- name: Start the postfix service
#  service: name=postfix state=started enabled=yes
#  tags: [service,postfix]

- include: ramdisk.yml
  tags: ramdisk

- include: ssh.yml
  tags: ssh

- include: composer.yml
  tags: composer

- include: mariadb.yml
  tags: mariadb

- include: nginx.yml
  tags: nginx

- include: supervisor.yml
  tags: supervisor

- include: php.yml
  tags: php

- include: vagrant.yml
  tags: vagrant

- include: zsh.yml
  when: homestead.use_zsh
  tags: zsh
