---

- name: Install Mariadb client and server
  apk: pkg={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-client

- name: Stop Mariadb
  service: name=mariadb enabled=yes state=stopped
  ignore_errors: yes

- name: Setup Mariadb
  shell: /etc/init.d/mariadb setup

- name: Start Mariadb
  service: name=mariadb enabled=yes state=started

- name: Setup Mariadb
  shell: echo -e "\ny\n{{ mariadb.root_password }}\n{{ mariadb.root_password }}\ny\ny\ny\ny" | /usr/bin/mysql_secure_installation

- name: Setup MySQL credentials for root user
  template: src=mysql.conf.j2 dest=~/.my.cnf owner=root mode=0600

- name: Setup MySQL credentials for vagrant user
  template: src=mysql.conf.j2 dest=/home/vagrant/.my.cnf owner=vagrant mode=0600

#- name: Customize MySQL configuration file - tmpdir to ramdisk
#  lineinfile: dest={{ mariadb.conf_path }} regexp="^#tmpdir\s*=\s/tmp" line="tmpdir = /run/shm" backrefs=yes
#  notify:
#   - restart mariadb

- name: Customize MySQL configuration file - disable bin_log
  lineinfile: dest={{ mariadb.conf_path }} regexp="^(log_bin\s*=\s*.*)" line="#\1" backrefs=yes
  notify:
   - restart mariadb

- name: Customize MySQL configuration file - disable bin_log
  lineinfile: dest={{ mariadb.conf_path }} regexp="^(log-bin\s*=\s*.*)" line="#\1" backrefs=yes
  notify:
   - restart mariadb

- name: Customize MySQL configuration file - disable bin_log_index
  lineinfile: dest={{ mariadb.conf_path }} regexp="^(log_bin_index\s*=\s*.*)" line="#\1" backrefs=yes
  notify:
   - restart mariadb

- name: Reduce innodb log file size
  lineinfile: dest={{ mariadb.conf_path }} regexp="^#(innodb_log_file_size\s*=\s*.*)" line="\1" backrefs=yes
  notify:
   - restart mariadb