---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Elasticsearch
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

- name: Start Elasticsearch
  service: name=elasticsearch state=started enabled=yes
