---

typo3_org_username: tuurlijk

typo3:
  cms:
    sites:
      6.2.cms.local.typo3.org: '6.2.*'
      6.2.12.cms.local.typo3.org: '6.2.12'
      7.1.cms.local.typo3.org: '7.1.*'
      dev-master.cms.local.typo3.org: '*'
    extensions:
      enabled:
        - scheduler
  neos:
    sites:
      1.2.neos.local.typo3.org: '1.2'
      dev-master.neos.local.typo3.org: 'dev-master'
