---
apt_cache_valid_time: 86400

php_ondrej_versions:
  - php5.6

php_ondrej_apt_packages:
  - php5.6

php_ondrej_pid_file: /var/run/php5-fpm.pid

php_ondrej_pools:
 - name: foo
   user: www-data
   group: www-data
   listen: 8000
   chdir: /

php_ondrej_pool_defaults:
  pm: dynamic
  pm.max_children: "{{ ansible_processor_vcpus * 2 }}"
  pm.start_servers: 2
  pm.min_spare_servers: 1
  pm.max_spare_servers: 3
  pm.status_path: /status

php_ondrej_default_pool:
  delete: yes
  name: www.conf

php_ondrej_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "ldap.max_links"
   section: "ldap"
   value: "1"

php_ondrej_config:
 - option: "error_log"
   section: "global"
   value: "/var/log/php5-fpm.log"
