---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart ntp
  service: name=ntp state=restarted

- name: restart postfix
  service: name=postfix state=restarted enabled=yes
