---

- name: Customize PHP Opcache configuration file
  ini_file: >
    dest=/etc/php/mods-available/opcache.ini
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items:
    - "{{ php_opcache_ini }}"
  notify:
   - restart php services
