---
- name: Comment out deprecated comment line with proper comment character
  lineinfile: >
    dest=/etc/php5/mods-available/xhprof.ini
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#xhprof.output_dir =', line: ';xhprof.output_dir = "/var/tmp/xhprof"' }
  ignore_errors: yes
  notify: restart php services
