---

- name: Checkout RustJason's xhprof
  git: repo=https://github.com/RustJason/xhprof.git version=php7 dest=/tmp/xhprof
  tags: test

- name: Compile xhprof module
  shell: >
    cd /tmp/xhprof/extension;
    phpize{{ item | regex_replace('^php(\d)\.(\d)', '\1.\2') }};
    ./configure --with-php-config=/usr/bin/php-config{{ item | regex_replace('^php(\d)\.(\d)', '\1.\2') }};
    make;
    make install;
  when: item | match('^php7\\.')
  with_items:
    - "{{ php_ondrej_versions }}"

- name: copy xhprof configuration file
  copy: src=xhprof.ini dest=/etc/php/{{ item | regex_replace('^php(\d)\.(\d)', '\1.\2') }}/mods-available/xhprof.ini force=no
  when: item | match('^php7\\.')
  with_items:
    - "{{ php_ondrej_versions }}"

- name: Enable xhprof in fpm context
  shell: >
    cd /etc/php/{{ item | regex_replace('^php(\d)\.(\d)', '\1.\2') }}/fpm/conf.d;
    ln -s /etc/php/{{ item | regex_replace('^php(\d)\.(\d)', '\1.\2') }}/mods-available/xhprof.ini 25-xhprof.ini
  when: item | match('^php7\\.')
  with_items:
    - "{{ php_ondrej_versions }}"
  ignore_errors: yes

- name: Comment out deprecated comment line with proper comment character
  lineinfile: >
    dest=/etc/php/{{ item[0] | regex_replace('^php(\d)\.(\d)', '\1.\2') }}/mods-available/xhprof.ini
    regexp="{{ item[1].regexp }}"
    line="{{ item[1].line }}"
    state=present
  when: item[0] | match('^php7\\.')
  with_nested:
    - "{{ php_ondrej_versions }}"
    - { regexp: '^#xhprof.output_dir =', line: ';xhprof.output_dir = "/var/tmp/xhprof"' }
  ignore_errors: yes
  notify: restart php services
