---
- hosts: all
  gather_facts: true
  become: yes
  vars_files:
    - configuration/Alpine/main.yml
    - configuration/Alpine/nginx.yml
    - configuration/Alpine/typo3.yml
  roles:
    - { role: alpine/nginx, tags: nginx }
    - { role: alpine/common, tags: common }
    - { role: typo3, tags: typo3 }
