---
- hosts: all
  gather_facts: true
  sudo: yes
  vars_files:
    - configuration/Development/main.yml
    - configuration/Development/nginx.yml
    - configuration/Development/php.yml
    - configuration/Development/websites.yml
    - configuration/Development/neos.yml
    - configuration/Development/typo3.yml
  roles:
    - { role: common,    tags: common }
    - { role: php-fpm,   tags: php-fpm }
    - { role: mariadb,   tags: mariadb }
    - { role: phpcommon, tags: phpcommon }
    - { role: phpbrew,   tags: phpbrew }
    - { role: hhvm,      tags: hhvm }
    - { role: composer,  tags: composer }
    - { role: typo3,     tags: typo3 }
    - { role: xhprof,    tags: xhprof }
    - { role: neos,      tags: neos }
    - { role: memcached, tags: memcached }
    - { role: nginx,     tags: nginx }
    - { role: nodejs,    tags: nodejs }
