---
- hosts: all
  gather_facts: true
  sudo: yes
  vars_files:
    - configuration/development/main.yml
    - configuration/development/nginx.yml
    - configuration/development/php.yml
    - configuration/development/websites.yml
    - configuration/development/typo3.yml
  roles:
    - { role: common,    tags: common }
    - { role: php-fpm,   tags: php-fpm }
    - { role: mariadb,   tags: mariadb }
    - { role: phpcommon, tags: phpcommon }
    - { role: hhvm,      tags: hhvm }
    - { role: composer,  tags: composer }
    - { role: typo3,     tags: typo3 }
    - { role: memcached, tags: memcached }
    - { role: nginx,     tags: nginx }
    - { role: nodejs,    tags: nodejs }
