---
- hosts: all
  gather_facts: true
  sudo: yes
  vars_files:
    - configuration/TYPOTry/main.yml
    - configuration/TYPOTry/nginx.yml
    - configuration/TYPOTry/php.yml
    - configuration/TYPOTry/websites.yml
    - configuration/TYPOTry/neos.yml
    - configuration/TYPOTry/typo3.yml
  roles:
    - { role: common,    tags: common }
    - { role: php-fpm,   tags: php-fpm }
    - { role: mariadb,   tags: mariadb }
    - { role: phpcommon, tags: phpcommon }
    - { role: composer,  tags: composer }
    - { role: typo3,     tags: typo3 }
    - { role: neos,      tags: neos }
    - { role: memcached, tags: memcached }
    - { role: nginx,     tags: nginx }
