---

- name: Setup TYPO3 CMS site directories
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item }} state=directory mode=0775
  with_items: typo3.cms.sites.keys()
  tags: typo3-cms-sites

- name: Create fileadmin directories
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item.key }}/fileadmin state=directory mode=0775
  with_dict: typo3.cms.sites
  tags: typo3-cms-directories

- name: Create typo3conf directories
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item.key }}/typo3conf state=directory mode=0775
  with_dict: typo3.cms.sites
  tags: typo3-cms-directories

- name: Create typo3temp directories
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item.key }}/typo3temp state=directory
  with_dict: typo3.cms.sites
  tags: typo3-cms-directories

- name: Add typo3_console composer.json to TYPO3 CMS 6.x and 7.x web roots
  sudo: vagrant
  template: src=cms/composer.json dest={{ typo3_webroot }}{{ item.key }}/composer.json
  when: item.key | match('^(6|7)\\.(\d)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-composer

- name: Add typo3_console composer.json to TYPO3 CMS 7.2 and up web roots
  sudo: vagrant
  template: src=cms/composer.json dest={{ typo3_webroot }}{{ item.key }}/composer.json
  when: item.key | match('^((7)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-composer

- name: Composer install typo3_console for TYPO3 CMS 6.x and 7.x web roots
  sudo: vagrant
  composer: command=install working_dir={{ typo3_webroot }}{{ item.key }}
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-composer

#- name: Composer install TYPO3 CMS 7.2 and up
#  sudo: vagrant
#  composer: command=install working_dir={{ typo3_webroot }}{{ item.key }}/typo3_src
#  when: item.key | match('^((7)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
#  with_dict: typo3.cms.sites
#  tags: typo3-cms-composer

- name: typo3_console installation of TYPO3
  sudo: vagrant
  shell: if [ ! -f {{ typo3_webroot }}{{ item.key }}/typo3conf/LocalConfiguration.php ]; then cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms install:setup --non-interactive --database-user-name=typo3 --database-user-password="{{ mariadb.password }}" --database-host-name=localhost --database-port=3306 --database-name={{ item.key | regex_replace('\\.', '_') }} --database-create=0 --admin-user-name=admin --admin-password="{{ mariadb.password }}" --site-name="TYPO3"; fi
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  ignore_errors: yes
  tags: typo3-cms-composer

- name: Flushing Caches
  sudo: vagrant
  command: rm -rf {{ typo3_webroot }}{{ item.key }}/typo3temp/Cache
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-composer

- name: typo3_console cache warmup
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms cache:warmup"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  ignore_errors: yes
  tags: typo3-cms-composer

- name: typo3_console install extension accountmanagement
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms extension:install accountmanagement"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  ignore_errors: yes

- name: typo3_console install extension distributionmanagement
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms extension:install distributionmanagement"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  ignore_errors: yes

- name: typo3_console create _cli_scheduler user
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms user:create --username _cli_scheduler"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  ignore_errors: yes

- name: typo3_console install extensions
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item[0] }} && ./typo3cms extension:install {{ item[1] }}"
  when: item[0] | match('^((6|7)\\.(\d)|dev-master|master|review)\\.') and typo3.cms.extensions.enabled is defined
  with_nested:
    - typo3.cms.sites.keys()
    - typo3.cms.extensions.enabled
  ignore_errors: yes

- name: typo3_console uninstall extensions
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item[0] }} && ./typo3cms extension:uninstall {{ item[1] }}"
  when: item[0] | match('^((6|7)\\.(\d)|dev-master|master|review)\\.') and typo3.cms.extensions.disabled is defined
  with_nested:
    - typo3.cms.sites.keys()
    - typo3.cms.extensions.disabled
  ignore_errors: yes

#- name: typo3_console update distribution list
#  sudo: vagrant
#  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms distribution:list"
#  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
#  with_dict: typo3.cms.sites
#  ignore_errors: yes
#
#- name: typo3_console install introduction distribution
#  sudo: vagrant
#  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms distribution:install introduction"
#  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
#  with_dict: typo3.cms.sites
#  ignore_errors: yes

- name: Setup git push for typo3_console CMS Sources
  sudo: vagrant
  shell: cd {{ typo3_webroot }}{{ item.key }}/typo3_src; git config remote.origin.push HEAD:refs/for/master;
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-legacy

- name: Setup git origin for typo3_console CMS Sources
  sudo: vagrant
  shell: cd {{ typo3_webroot }}{{ item.key }}/typo3_src; git remote set-url origin {{ typo3_cms_src_repository }}
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-legacy

- name: Setup git commit message for typo3_console CMS Sources
  sudo: vagrant
  copy: src=git-commit-msg dest={{ typo3_webroot }}{{ item.key }}/typo3_src/.git/hooks/commit-msg force=no
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-legacy

- name: Create AdditionalConfiguration.php
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php state=touch mode=0664
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-localconf

- name: Ensure AdditionalConfiguration.php contains starting php tag
  sudo: vagrant
  lineinfile: dest={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php line="<?php" insertbefore=BOF
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-localconf

- name: Add trustedHostsPattern to AdditionalConfiguration.php
  sudo: vagrant
  lineinfile: dest={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php line="$GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] = '.*';" insertafter="<\?php"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  tags: typo3-cms-localconf

- name: Add mailcatcher smtp configuration to AdditionalConfiguration.php
  sudo: vagrant
  lineinfile: dest={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php line="$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport'] = 'smtp';" insertafter="<\?php"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  when: mailcatcher_enable
  tags: typo3-cms-localconf

- name: Add mailcatcher smtp port configuration to AdditionalConfiguration.php
  sudo: vagrant
  lineinfile: dest={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php line="$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_server'] = 'localhost:1025';" insertafter="<\?php"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  when: mailcatcher_enable
  tags: typo3-cms-localconf

- name: Enable error reporting in AdditionalConfiguration.php
  sudo: vagrant
  lineinfile: dest={{ typo3_webroot }}{{ item.key }}/typo3conf/AdditionalConfiguration.php line="$GLOBALS['TYPO3_CONF_VARS']['SYS']['displayErrors'] = TRUE;" insertafter="<\?php"
  when: item.key | match('^((6|7)\\.(\d)|dev-master|master|review)\\.')
  with_dict: typo3.cms.sites
  when: mailcatcher_enable
  tags: typo3-cms-localconf

- name: Enable install tool for CMS Sources
  sudo: vagrant
  file: path={{ typo3_webroot }}{{ item.key }}/typo3conf/ENABLE_INSTALL_TOOL state=touch mode=0664
  with_dict: typo3.cms.sites
  tags: typo3-cms-installtool

- name: Create ramdisk directories to offload typo3temp to ramdisk
  file: path=/mnt/typo3cache/{{ item }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_items: typo3.cms.sites.keys()
  tags: typo3-cms-ramdisk

- name: Make fstab entries for TYPO3 CMS typo3temp
  mount: src=/mnt/typo3cache/{{ item }} name={{ typo3_webroot }}{{ item }}/typo3temp/ fstype=none opts=bind,noauto state=present
  with_items: typo3.cms.sites.keys()
  tags: typo3-cms-ramdisk

- name: Mount bind TYPO3 CMS typo3temp ramdisks
  shell: if ! mountpoint -q "{{ typo3_webroot }}{{ item }}/typo3temp"; then mount "/mnt/typo3cache/{{ item }}"; fi
  with_items: typo3.cms.sites.keys()
  tags: typo3-cms-ramdisk
