---

- name: Setup cron scheduler tasks for TYPO3 CMS
  cron: name="Scheduler task for {{ item.key }}"
        user=vagrant
        job="php {{ typo3_webroot }}{{ item.key }}/typo3/cli_dispatch.phpsh scheduler 2>/dev/null > /dev/null "
  with_dict: typo3.cms.sites

- name: Setup cron job for typo3temp ramfs automounter
  cron: name="Run typo3temp ramfs automounter" job="[ -x /root/bin/mountTypo3Temp.sh ] && /root/bin/mountTypo3Temp.sh 2>/dev/null > /dev/null "

- name: Setup cron job for touching 'enable install tool' files
  cron: name="Touch enable install tool files" job="[ -x /root/bin/createEnableInstallToolFiles.sh ] && /root/bin/createEnableInstallToolFiles.sh 2>/dev/null > /dev/null "
  tags: typo3-cms-installtool
