---

nginx_user: vagrant

nginx_http_params:
  - index index.php index.html
  - charset utf-8
  - fastcgi_read_timeout 240
  - access_log off
  - open_file_cache max=1000 inactive=20s
  - open_file_cache_valid 30s
  - open_file_cache_min_uses 2
  - open_file_cache_errors on
  - keepalive_requests 1000

nginx_configs:
  upstream_php:
    - upstream php { server unix:/var/run/php5-fpm.sock; }

nginx_fastcgi: |
  client_max_body_size 20M;
  add_header X-TYPO3-backend $upstream;
  try_files $uri $uri/ /index.php?$args;
  location ~ \.php$ {
    try_files     $uri =404;
    fastcgi_pass  $upstream;
    fastcgi_index index.php;
    fastcgi_param FLOW_CONTEXT Development;
    fastcgi_param FLOW_REWRITEURLS 1;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include       fastcgi_params;
  }

nginx_typo3_404_redirect: |
  location @404 {
    rewrite ^ $scheme://local.typo3.org;
  }

nginx_neos_404_redirect: |
  location @404 {
    rewrite ^ $scheme://local.neos.io;
  }

nginx_neos_resources: |
  location ~ "^/_Resources/Persistent/" {
    if ($version ~ (1.0|1.1|1.2)) {
      expires max;
      rewrite "(.{40})/.+\.(.+)" /_Resources/Persistent/$1.$2 break;
      rewrite "([a-z0-9]+/(.+/)?[a-f0-9]{40})/.+\.(.+)" /_Resources/Persistent/$1.$2 break;
    }
  }
