---

typo3_org_username: nobody

typo3_composer_install_dev: 'no'

typo3:
  cms:
    sites:
      6.2.21.local.typo3.org: '6.2.21'
      7.6.5.local.typo3.org: '7.6.5'
      8.0.1.local.typo3.org: '8.0.1'
    extensions:
      enabled:
        - scheduler
