---

typo3_org_username: nobody

typo3_composer_install_dev: 'no'

typo3:
  cms:
    sites:
      6.2.17.local.typo3.org: '6.2.17'
      7.6.2.local.typo3.org: '7.6.2'
    extensions:
      enabled:
        - scheduler
